### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by polarpixel** [skerbis/redaxo_piwik_tracker#7]
Eine Idee: Beim Rumklicken in PIWIK stieß ich auf die Widgets, die ich bis dato nicht beachtet hatte. Wäre das nicht eine schicke Sache, wenn man sich die gewünschten Widget-Codes (die ja de facto nur Iframe sind) in Eurem AddOn einfügen ließen? Dann könnte man sich innerhalb von Redaxo eine Statistik-Seite konfigurieren mit den gewünschten Widgets.
Vielleicht auch was fürs Dashboard-AddOn? Doch die Verwaltung dafür wäre im piwik_tracker angesiedelt.

**Comment by skerbis** [comment]
Grundsätzlich keine schlechte Idee. Mal sehen. Unterstützung ist erwünscht.

**Comment by skerbis** [comment]
Für später notiert.
